name: OpenGL Playground CI

on:
  push

permissions:
  contents: read

jobs:
  behaviours:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Haskell
      run: |
        sudo apt-get update
        curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
        
        ghcup install ghc 8.10.7
        ghcup install cabal 3.6.2.0
        
        ghcup set ghc 8.10.7
        ghcup set cabal 3.6.2.0

    - name: Dependencies
      run: |
        cabal update
        cabal build all --only-dependencies --enable-tests --enable-benchmarks

    - name: Build
      run: cabal build behaviours --enable-tests

    - name: Test
      run: cabal test behaviours
