name: OpenGL Playground CI

on:
  push

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-haskell@v1.1
      with:
        ghc-version: '8.10.1'

    - name: Build `behaviours` dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks

    - name: Build `behaviours`
      run: cabal build behaviours --enable-tests

    - name: Test `behaviours`
      run: cabal test behaviours
